FROM node:20-alpine

# Install pnpm secara global
RUN npm install -g pnpm

WORKDIR /app

# Copy manifest dan install dependensi
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--", "--host"]